# Generated by Django 4.2.7 on 2023-12-05 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bgimages',
            old_name='main_headding',
            new_name='main_heading',
        ),
        migrations.RenameField(
            model_name='bgimages',
            old_name='sub_headding',
            new_name='sub_heading',
        ),
    ]
