# Generated by Django 4.2.7 on 2023-12-16 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_clients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bgimages',
            name='image',
            field=models.ImageField(upload_to='backgroundimages/'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='image',
            field=models.ImageField(upload_to='category/'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='image',
            field=models.ImageField(upload_to='clients/'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(upload_to='products/'),
        ),
    ]
