# Generated by Django 4.2.7 on 2023-12-18 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_about_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='about_story',
            name='is_show',
            field=models.BooleanField(default=True),
        ),
    ]
