# Generated by Django 4.2.7 on 2023-12-25 17:07

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_contacts_alter_careers_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about_story',
            name='is_show',
        ),
        migrations.AlterField(
            model_name='about_story',
            name='body',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
    ]
